---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  namespace: test-ns
  labels:
    app: myapp
    type: appserver
spec:
  replicas: 3
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: myapp
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 9090
...              
