---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: httpd-deployment
  labels: 
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd 
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      toleration:
        key: slave1
        value: imran1
        operator: Equal
        effect: NoSchedule          
...

#here though the nodes/slave is been tainted than also the Pod will be deploy on the tainted nodes/slaves
kubectl taint nodes "node_name" node1=imran1:Noschedule (Taint Node Command) 
                                #  KEY  VALUE  EFFEC
#kubectl taint nodes "node_name" node1=imran1:Noschedule- (unTaint the Node Command)                                    