# Basic NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: basic-nodeport
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080

---
# NodePort with Auto-assigned Port
apiVersion: v1
kind: Service
metadata:
  name: auto-nodeport
spec:
  type: NodePort
  selector:
    app: api-app
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort will be auto-assigned in range 30000-32767

---
# Multi-Port NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: multi-port-nodeport
spec:
  type: NodePort
  selector:
    app: full-stack-app
  ports:
  - name: frontend
    port: 80
    targetPort: 3000
    nodePort: 30080
  - name: api
    port: 8080
    targetPort: 8080
    nodePort: 30081
  - name: admin
    port: 9090
    targetPort: 9090
    nodePort: 30090

---
# NodePort with Session Affinity
apiVersion: v1
kind: Service
metadata:
  name: sticky-nodeport
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: stateful-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30082

---
# Deployment for NodePort Testing
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx:1.20
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

---
# Service for the Test Deployment
apiVersion: v1
kind: Service
metadata:
  name: nodeport-test-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30085