---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deployment 
  namespace: test-ns
  labels:
    type: db 
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template: 
    metadata:
      name: mydb-pod
      labels:
        type: db 
    spec:
      containers:
        - name: mydb
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abcd
...