apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ghost-deployment
  labels:
    type: cms
spec:
  replicas: 2
  selector:
    matchLabels:
      type: cms
  template:
    metadata:
      name: ghost-pod
      labels:
        type: cms
        author: imran
    spec:
      containers:
        - name: myghost
          image: ghost:latest
          ports:
            - containerPort: 2368
              hostPort: 9999
          env:
            - name: NODE_ENV
              value: development
