apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    author: imran
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxy
    author: imran    