apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: test-ns
  labels:
    author: imran
spec:
  type: LoadBalancer
  selector:
    author: imran
    type: webserver
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
