# Pods with Different Labels
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
    tier: web
    version: v1.0
    environment: production
spec:
  containers:
  - name: nginx
    image: nginx:1.20

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
    tier: api
    version: v1.1
    environment: production
spec:
  containers:
  - name: api
    image: node:16

---
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database
    tier: data
    version: v2.0
    environment: production
spec:
  containers:
  - name: postgres
    image: postgres:13

---
# ReplicaSet using Label Selectors
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        tier: frontend
        version: v1.0
    spec:
      containers:
      - name: web
        image: nginx:1.20

---
# Service using Selectors
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: web
    tier: frontend
  ports:
  - port: 80
    targetPort: 80

---
# Deployment with Advanced Selectors
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-deployment
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: [web, frontend]
    - key: version
      operator: Exists
    - key: deprecated
      operator: DoesNotExist
  template:
    metadata:
      labels:
        app: web
        version: v1.0
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx:1.20

---
# Pod with Node Selector
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: nginx
    image: nginx:1.20