# Deployment with Revision History
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-demo
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 3
  revisionHistoryLimit: 5  # Keep 5 previous versions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: rollback-demo
  template:
    metadata:
      labels:
        app: rollback-demo
        version: "v1.0"
    spec:
      containers:
      - name: app
        image: nginx:1.19  # Initial version
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "1.0"
        - name: RELEASE_DATE
          value: "2023-01-01"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---