---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deployment 
  labels:
    type: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template: 
    metadata:
      name: mydb-pod
      labels:
        type: db 
    spec:
      containers:
        - name: mydb
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: a
...