---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    type: CI_CD
    author: imran
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090

...          