---
apiVersion: v1
kind: Pod
metadata: 
  name: postgress-pod
  labels:
    type: db
    author: imran
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: imran 
        - name: POSTGRES_DB
          value: mydb
        - name: POSGTRES_USER
          value: myuser    
...
