---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: test-ns
  labels:
    author: imran
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080

...          

