---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: test-ns
  labels:
    author: imran
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd

...          
