---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment
  labels:
    author: imran
    type: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-deployment
  template:
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: my-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc
...        